version: "2"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: catalina.sh run
    ports:
      - "8080:8080"
    volumes:
      - "/srv/vase:/data"
      - "/srv/data:/mnt/chelonium"
